name: Deploy frontend to GCP

on:
  push:
    branches: [ "deploy-frontend" ]

jobs:
  deploy:
    name: Build and Deploy Frontend to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: anserjufe-319714

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-frontend:latest .

      - name: Push Docker Image to Artifact Registry
        run: docker push southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy product-manager-frontend \
            --image southamerica-east1-docker.pkg.dev/anserjufe-319714/docker-repo/product-manager-frontend:latest \
            --region southamerica-east1 \
            --memory 256Mi \
            --platform managed \
            --port 80 \
            --allow-unauthenticated
